CREATE DATABASE AI_ANALYTICS_DB;

USE DATABASE AI_ANALYTICS_DB;

CREATE SCHEMA TEMP_SCHEMA;

USE SCHEMA TEMP_SCHEMA;

CREATE WAREHOUSE AI_WH
WITH
WAREHOUSE_SIZE = 'XSMALL'
AUTO_SUSPEND = 60
AUTO_RESUME = TRUE;

USE WAREHOUSE AI_WH;